name: aws-asignment
on:
  push:
    branches:
    - devops
jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Install dependencies (optional)
        
        run: |
          sudo apt update

      - name: Update application code on EC2
        run: |
        
          cd aws-devops-intern/

          git pull origin main
          
      - name: Create Gunicorn service file (optional)
        run: |
          echo '... (Gunicorn service file content) ...' > gunicorn.service 
          sudo mv gunicorn.service /etc/systemd/system/ 
      - name: Reload systemd (if using a Gunicorn service file)
        run: |
          sudo systemctl daemon-reload

      - name: Start or Restart Gunicorn service (if using a Gunicorn service file)
        run: |
          sudo systemctl start gunicorn.service  # Start the service (or 'restart' for existing service)

      - name: Reload Nginx configuration
        run: |
          sudo nginx -s reload
 
